---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  annotations:
    linkerd.io/inject: enabled
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: api
        swiss.dev/logging: json
    spec:
      containers:
        - name: api
          image: ghcr.io/cfi2017/sgbf/api:sha-51d6143
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: SGBF__TRACING__ERROR_REPORTING__SENTRY_DSN
              value: "https://952ffd64359f4f2e83b283faacdd545f@sentry.service.cloud.swiss.dev/3"
            - name: RUST_LOG
              value: "info"
            - name: SGBF__CACHE__USERNAME
              valueFrom:
                secretKeyRef:
                  name: cache
                  key: username
            - name: SGBF__CACHE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cache
                  key: password
            - name: SGBF__FIREBASE__PROJECT
              value: "sgbf-system"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/sgbf/service-account.json"
          volumeMounts:
          - name: service-account
            mountPath: /etc/sgbf/
            readOnly: true

      volumes:
        - name: service-account
          secret:
            secretName: firebase
            items:
            - key: service-account.json
              path: service-account.json

      restartPolicy: Always