---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  annotations:
    linkerd.io/inject: enabled
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
        swiss.dev/logging: json
    spec:
      containers:
        - name: api
          image: ghcr.io/cfi2017/sgbf:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
      restartPolicy: Always