apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: ghcr.io/cfi2017/sgbf/api
  newName: sha-955f02f
- name: ghcr.io/cfi2017/sgbf/frontend
  newName: sha-955f02f

resources:
- ambassador.yaml
- ./api/deploy.yaml
- ./frontend/deploy.yaml
- ./api/service.yaml
- ./frontend/service.yaml
