apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: ghcr.io/cfi2017/sgbf/api
  newName: ghcr.io/cfi2017/sgbf/api
  newTag: sha-bb22ce5
- name: ghcr.io/cfi2017/sgbf/frontend
  newName: ghcr.io/cfi2017/sgbf/frontend
  newTag: sha-bb22ce5

resources:
- ambassador.yaml
- ./api/deploy.yaml
- ./frontend/deploy.yaml
- ./api/service.yaml
- ./frontend/service.yaml
