apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/cfi2017/sgbf/api
    newTag: latest
  - name: ghcr.io/cfi2017/sgbf/frontend
    newTag: latest

resources:
  - ambassador.yaml
  - ./api/deploy.yaml
  - ./frontend/deploy.yaml
  - ./api/service.yaml
  - ./frontend/service.yaml